### PR TITLE
Fix build for MacOS by explicitly linking libssl.

### PR DESCRIPTION
**Pull request by hbowden**

### CODE REVIEW

**Comment by lgrahl** [comment]
Mac OS builds work fine for me (at least in Travis - I don't own a Mac). I also don't think it's a good idea to hard-code linking against `/usr/local/lib`.

**Comment by alfredh** [comment]
there should be no need to do this. The openssl is detected automatically,
if not you can force it:

```
$ make USE_OPENSSL=1
```

can you please send me the output of `make info` ?


/Alfred

**Comment by hbowden** [comment]
Here's the output from make info: 
```bash
nahs-MBP:re nah$ make info
info - re version 0.5.4
  MODULES:       sip sipevent sipreg sipsess uri http httpauth msg websock stun turn ice natbd rtp sdp jbuf telev dns md5 crc32 sha hmac base64 udp sa net tcp tls list mbuf hash fmt tmr main mem dbg sys lock mqueue mod conf bfcp aes srtp odict json
  MACHINE:       x86_64-apple-darwin16.4.0
  ARCH:          x86_64
  OS:            darwin
  BUILD:         build-x86_64
  CCACHE:        
  CC:            clang 8.1
  CFLAGS:        -Wall -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wbad-function-cast -Wsign-compare -Wnested-externs -Wshadow -Waggregate-return -Wcast-align -g -fPIC -dynamic -DDARWIN -Wshorten-64-to-32 -DOS="darwin" -std=c99 -pedantic -DARCH="x86_64" -DUSE_OPENSSL -DUSE_TLS -DUSE_OPENSSL_DTLS -DUSE_DTLS -DUSE_OPENSSL_SRTP -DUSE_DTLS_SRTP -DUSE_ZLIB -DHAVE_PTHREAD -DHAVE_GETIFADDRS -DHAVE_STRERROR_R -DHAVE_GETOPT -DHAVE_INTTYPES_H -DHAVE_NET_ROUTE_H -DHAVE_SYS_SYSCTL_H -DHAVE_STDBOOL_H -DHAVE_INET6 -DHAVE_RESOLV -DHAVE_SYSLOG -DHAVE_FORK -DHAVE_INET_NTOP -DHAVE_PWD_H -DHAVE_SELECT -DHAVE_SELECT_H -DHAVE_SETRLIMIT -DHAVE_SIGNAL -DHAVE_SYS_TIME_H -DHAVE_KQUEUE -DHAVE_UNAME -DHAVE_UNISTD_H -DHAVE_STRINGS_H -DHAVE_GAI_STRERROR -DVERSION="0.5.4"  -Iinclude -DHAVE_ROUTE_LIST
  DFLAGS:        -MD
  LFLAGS:        -fPIC  -lssl -L/usr/local/lib -framework SystemConfiguration -framework CoreFoundation
  SH_LFLAGS:     -dynamiclib -current_version 0.5.4 -compatibility_version 0.5.4
  MOD_LFLAGS:    -undefined dynamic_lookup
  APP_LFLAGS:    
  LIBS:          -lresolv -lssl -lcrypto -lz -lpthread
  LIBRE_MK:      
  LIBRE_INC:     ../re/include
  LIBRE_SO:      ../re
  USE_OPENSSL:   yes
  USE_OPENSSL_AES:   yes
  USE_OPENSSL_HMAC:  yes
  USE_TLS:       yes
  USE_DTLS:      yes
  USE_DTLS_SRTP: yes
  USE_ZLIB:      yes
  GCOV:          
  GPROF:         
  CROSS_COMPILE: 
  SYSROOT:       /usr
  SYSROOT_ALT:   
  LIB_SUFFIX:    .dylib
  MOD_SUFFIX:    .so
  BIN_SUFFIX:    
nahs-MBP:re nah$ 
```

**Comment by hbowden** [comment]
Also I tried running make as you suggested `make USE_OPENSSL=1` and I still get the linking errors: 
```bash 
Undefined symbols for architecture x86_64:
  "_EVP_aes_128_ctr", referenced from:
      _aes_alloc in aes.o
  "_EVP_aes_192_ctr", referenced from:
      _aes_alloc in aes.o
  "_EVP_aes_256_ctr", referenced from:
      _aes_alloc in aes.o
  "_SSL_CTX_set_tlsext_use_srtp", referenced from:
      _tls_set_srtp in tls.o
  "_SSL_export_keying_material", referenced from:
      _tls_srtp_keyinfo in tls.o
  "_SSL_get_selected_srtp_profile", referenced from:
      _tls_srtp_keyinfo in tls.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by hbowden** [comment]
@lgrahl Your probably right about hardcoding being a bad idea, this might just be a problem with my setup or if not a documentation update might be the best approach. I'm going to see if I can recreate on another mac machine. In the mean time here's more info on my setup: 
```
MacOS: 10.12.3
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /usr/local/bin

**Comment by alfredh** [comment]
is openssl from Macports or Homebrew installed on your machine?

if so, which version?

**Comment by hbowden** [comment]
Just realized what might be the problem, so it's Libressl 2.5.0 not openssl, so maybe thats why it's not be detected? 
```
openssl version -a
LibreSSL 2.5.0
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/usr/local/etc/ssl"
```

**Comment by alfredh** [comment]
perhaps you are using header files from one version of openssl and
linking to another version of opensls ?

I have tested libre with libressl on both OpenBSD and OSX and it works fine.

you can try this:

```
sudo port deactivate openssl

brew uninstall openssl
brew uninstall openssl@1.1
brew install libressl

cd re
make SYSROOT_ALT= USE_OPENSSL=1 EXTRA_CFLAGS=-I/usr/local/Cellar/libressl/2.5.4/include EXTRA_LFLAGS=-L/usr/local/Cellar/libressl/2.5.4/lib
```

/Alfred

**Pull request closed without merging**
