### PR TITLE
Add ability to print SIP trace

### PR DESCRIPTION
**Pull request by quentusrex**
Resolves https://github.com/creytiv/re/issues/151

### CODE REVIEW

**Comment by quentusrex** [comment]
@alfredh Just pinging here to refresh memory, as we worked on this patch a little while back.

**Comment by alfredh** [comment]
thanks @quentusrex :)

yes I did not forget about it. we will see how to proceed with this one.

**Comment by alfredh** [comment]
an alternative solution would be to expose the UDP/TCP sockets in the
SIP transport API.

then the application could use UDP/TCP helpers to fetch all outgoing/incoming
packets.

**Comment by alfredh** [comment]
we have decided not to apply this patch.

we have a better solution for this, but we are not sure when it will be added.

for now you can keep the patch in your fork.

**Pull request closed without merging**
