### PR TITLE
remove gai_strerror stub

### PR DESCRIPTION
**Pull request by alfredh**
please dont merge yet.

| Platform   | Arch | libc      | Result |
| --- | --- | --- | --- |
| Android NDK r16b  | arm   |    bionic     | OK |
| Debian 7  | i386   |    libc6 2.13-38     | OK |
| Debian 8 | x86_64 | libc 2.19-18 | OK
| Debian    |    |    libc6 2.27-8     | OK |
| MacOSX 10.12   | x86_64 |    | OK |
| Mingw gcc 4.9.1 | win32 | win32 | OK |
| OpenBSD 6.4       | x86_64 |  | OK |
| Windows | x86_64 |  | OK |

### CODE REVIEW

**Comment by alfredh** [comment]
this patch should be tested on Windows.

@Encamy is this something you could help with ?

**Comment by alfredh** [comment]
we are trying to find out if `gai_strerror` is available on windows.

if this branch compiles for you, then the test is ok.

**Comment by Encamy** [comment]
Compilation was successful. Windows have implementation of gai_strerror (defined in header WS2tcpip.h)
<details>
<summary> Compilation log</summary>
1>------ Rebuild All started: Project: re-win32, Configuration: Debug Win32 ------<br>
1>stub.c<br>
1>b64.c<br>
1>attr.c<br>
1>c:\baresip\re\src\bfcp\attr.c(131): warning C4267: 'function': conversion from 'size_t' to 'uint8_t', possible loss of data<br>
1>conn.c<br>
1>msg.c<br>
1>reply.c<br>
1>request.c<br>
1>conf.c<br>
1>crc32.c<br>
1>dbg.c<br>
1>client.c<br>
1>c:\baresip\re\src\dns\client.c(696): warning C4267: 'function': conversion from 'size_t' to 'u_short', possible loss of data<br>
1>cstr.c<br>
1>dname.c<br>
1>c:\baresip\re\src\dns\dname.c(76): warning C4267: 'function': conversion from 'size_t' to 'u_short', possible loss of data<br>
1>c:\baresip\re\src\dns\dname.c(121): warning C4267: '=': conversion from 'size_t' to 'uint8_t', possible loss of data<br>
1>c:\baresip\re\src\dns\dname.c(129): warning C4267: '=': conversion from 'size_t' to 'uint8_t', possible loss of data<br>
1>hdr.c<br>
1>ns.c<br>
1>rr.c<br>
1>c:\baresip\re\src\dns\rr.c(169): warning C4267: '=': conversion from 'size_t' to 'uint16_t', possible loss of data<br>
1>rrlist.c<br>
1>srv.c<br>
1>ch.c<br>
1>hexdump.c<br>
1>pl.c<br>
1>print.c<br>
1>prm.c<br>
1>regex.c<br>
1>str.c<br>
1>str_error.c<br>
1>time.c<br>
1>unicode.c<br>
1>func.c<br>
1>hash.c<br>
1>hmac.c<br>
1>hmac_sha1.c<br>
1>basic.c<br>
1>digest.c<br>
1>auth.c<br>
1>client.c<br>
1>msg.c<br>
1>server.c<br>
1>cand.c<br>
1>candpair.c<br>
1>chklist.c<br>
1>comp.c<br>
1>connchk.c<br>
1>ice.c<br>
1>icem.c<br>
1>icesdp.c<br>
1>icestr.c<br>
1>stunsrv.c<br>
1>util.c<br>
1>jbuf.c<br>
1>decode.c<br>
1>c:\baresip\re\src\json\decode.c(69): warning C4244: '=': conversion from 'long double' to 'int64_t', possible loss of data<br>
1>c:\baresip\re\src\json\decode.c(157): warning C4244: '=': conversion from 'long double' to 'int64_t', possible loss of data<br>
1>decode_odict.c<br>
1>encode.c<br>
1>list.c<br>
1>lock.c<br>
1>init.c<br>
1>main.c<br>
1>method.c<br>
1>mbuf.c<br>
1>md5.c<br>
1>wrap.c<br>
1>mem.c<br>
1>mod.c<br>
1>dll.c<br>
1>mqueue.c<br>
1>pipe.c<br>
1>ctype.c<br>
1>param.c<br>
1>filtering.c<br>
1>genalg.c<br>
1>hairpinning.c<br>
1>lifetime.c<br>
1>mapping.c<br>
1>natstr.c<br>
1>if.c<br>
1>net.c<br>
1>c:\baresip\re\src\net\net.c(44): warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings<br>
1>c:\program files (x86)\windows kits\10\include\10.0.17134.0\um\winsock2.h(2218): note: see declaration of 'gethostbyname'<br>
1>netstr.c<br>
1>rt.c<br>
1>sock.c<br>
1>sockopt.c<br>
1>wif.c<br>
1>entry.c<br>
1>odict.c<br>
1>type.c<br>
1>fb.c<br>
1>member.c<br>
1>ntp.c<br>
1>pkt.c<br>
1>c:\baresip\re\src\rtp\pkt.c(184): warning C4267: 'function': conversion from 'size_t' to 'uint8_t', possible loss of data<br>
1>c:\baresip\re\src\rtp\pkt.c(237): warning C4267: '=': conversion from 'size_t' to 'uint16_t', possible loss of data<br>
1>rr.c<br>
1>rtcp.c<br>
1>rtp.c<br>
1>sdes.c<br>
1>sess.c<br>
1>source.c<br>
1>ntop.c<br>
1>printaddr.c<br>
1>pton.c<br>
1>sa.c<br>
1>attr.c<br>
1>format.c<br>
1>media.c<br>
1>msg.c<br>
1>session.c<br>
1>str.c<br>
1>util.c<br>
1>sha1.c<br>
1>listen.c<br>
1>msg.c<br>
1>notify.c<br>
1>subscribe.c<br>
1>reg.c<br>
1>accept.c<br>
1>ack.c<br>
1>close.c<br>
1>connect.c<br>
1>info.c<br>
1>listen.c<br>
1>modify.c<br>
1>reply.c<br>
1>request.c<br>
1>sess.c<br>
1>addr.c<br>
1>auth.c<br>
1>contact.c<br>
1>cseq.c<br>
1>ctrans.c<br>
1>dialog.c<br>
1>keepalive.c<br>
1>keepalive_udp.c<br>
1>msg.c<br>
1>reply.c<br>
1>request.c<br>
1>sip.c<br>
1>strans.c<br>
1>transp.c<br>
1>via.c<br>
1>misc.c<br>
1>replay.c<br>
1>srtcp.c<br>
1>srtp.c<br>
1>stream.c<br>
1>addr.c<br>
1>attr.c<br>
1>c:\baresip\re\src\stun\attr.c(168): warning C4267: 'function': conversion from 'size_t' to 'u_short', possible loss of data<br>
1>ctrans.c<br>
1>dnsdisc.c<br>
1>hdr.c<br>
1>ind.c<br>
1>keepalive.c<br>
1>msg.c<br>
1>c:\baresip\re\src\stun\msg.c(307): warning C4267: '=': conversion from 'size_t' to 'uint16_t', possible loss of data<br>
1>c:\baresip\re\src\stun\msg.c(328): warning C4267: '=': conversion from 'size_t' to 'uint16_t', possible loss of data<br>
1>rep.c<br>
1>req.c<br>
1>stun.c<br>
1>stunstr.c<br>
1>daemon.c<br>
1>endian.c<br>
1>fs.c<br>
1>rand.c<br>
1>sleep.c<br>
1>sys.c<br>
1>tcp.c<br>
1>tcp_high.c<br>
1>telev.c<br>
1>tmr.c<br>
1>chan.c<br>
1>perm.c<br>
1>turnc.c<br>
1>c:\baresip\re\src\turn\turnc.c(281): warning C4267: '=': conversion from 'size_t' to 'uint16_t', possible loss of data<br>
1>c:\baresip\re\src\turn\turnc.c(488): warning C4267: '=': conversion from 'size_t' to 'uint16_t', possible loss of data<br>
1>mcast.c<br>
1>udp.c<br>
1>ucmp.c<br>
1>uri.c<br>
1>uric.c<br>
1>Iphlpapi.lib(IPHLPAPI.DLL) : warning LNK4006: __NULL_IMPORT_DESCRIPTOR already defined in ws2_32.lib(WS2_32.dll); second definition ignored<br>
1>Iphlpapi.lib(IPHLPAPI.DLL) : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library<br>
1>re.vcxproj -> C:\baresip\re\mk\win32\..\..\Win32\Debug\bin\re-win32.lib<br>
1>Done building project "re.vcxproj".<br>
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========<br>
</details>

**Comment by alfredh** [comment]
@Encamy many thanks for your help.

so it looks like all the supported platforms have `gai_strerror`, which means
that we should remove the stub (an old hack).

**Pull request merged**
